import { CreditCard, ExternalLink, ShieldCheck } from "lucide-react";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { getSquareConnection, ticketingProviderName } from "@/lib/payments/connection";
import { disconnectSquare } from "./actions";

export default async function PaymentSettings({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) { const query = await searchParams; const connection = await getSquareConnection(); const mock = ticketingProviderName() === "mock";
  return <><AdminPageHeader eyebrow="Payments" title="Payment settings" description="Connect the Square account that will receive ticket revenue. Passwords and card data are never stored by GOOM." />{query.connected && <p className="admin-success">Square connected successfully.</p>}{query.error && <p className="admin-form-error">Square could not be connected. Check the application settings and try again.</p>}
  {mock && <div className="admin-setup-note"><strong>Development payment simulator is active</strong><p>No real charges can be made. Change PAYMENT_PROVIDER to square when you are ready to test Square Sandbox.</p></div>}
  <section className="payment-connection-card"><div className="payment-provider-mark"><CreditCard /></div><div><span>Payment provider</span><h2>Square</h2><p><ShieldCheck />OAuth connection · encrypted server-side storage</p></div><div className="payment-connection-status"><em className={connection?.connected ? "connected" : ""}>{connection?.connected ? "Connected" : "Not connected"}</em>{connection?.connected && <small>{connection.location_name || connection.location_reference}<br />Account {connection.account_reference}</small>}</div><div className="payment-connection-actions"><a href="/api/payments/square/connect" className="admin-primary-button">{connection?.connected ? "Reconnect" : "Connect Square"}<ExternalLink /></a>{connection?.connected && <form action={disconnectSquare}><button className="admin-danger-button">Disconnect</button></form>}</div></section>
  <section className="admin-record-card payment-setup-guide"><h2>Before enabling live sales</h2><ol><li>Create the Square application in the Developer Dashboard.</li><li>Register the exact OAuth callback and webhook URLs documented in the project README.</li><li>Subscribe to payment.created, payment.updated, refund.created and refund.updated.</li><li>Connect here first in Sandbox, complete a test purchase, scan its QR, then repeat with production credentials.</li></ol></section></>;
}
