import Link from "next/link";
import { notFound } from "next/navigation";
import { Clock3, Landmark, MessageCircle, ShieldCheck } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { CheckoutPayment } from "@/components/ticketing/CheckoutPayment";
import { money } from "@/lib/ticketing/core";

export default async function CheckoutPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; const admin = createAdminClient(); if (!admin) notFound();
  const { data: order } = await admin.from("orders").select("*").eq("public_token", token).maybeSingle(); if (!order) notFound();
  const [{ data: event }, { data: items }, { data: transferSettings }] = await Promise.all([admin.from("events").select("title,slug,date,venue").eq("id", order.event_id).single(), admin.from("order_items").select("quantity,unit_price_cents,total_cents,ticket_type_id").eq("order_id", order.id), order.payment_provider === "etransfer" ? admin.from("site_settings").select("key,value").in("key", ["etransfer_email", "etransfer_whatsapp", "email", "whatsapp"]) : Promise.resolve({ data: [] })]);
  const typeIds = (items || []).map((item) => item.ticket_type_id); const { data: types } = typeIds.length ? await admin.from("ticket_types").select("id,name").in("id", typeIds) : { data: [] }; const names = new Map((types || []).map((type) => [type.id, type.name]));
  const settings = Object.fromEntries((transferSettings || []).map((setting) => [setting.key, setting.value || ""]));
  const transferEmail = settings.etransfer_email || settings.email || "";
  const transferWhatsapp = settings.etransfer_whatsapp || settings.whatsapp || "";
  const whatsappDigits = transferWhatsapp.replace(/\D/g, "");
  const whatsappMessage = encodeURIComponent(`Hello GOOM, I am sending proof of e-Transfer for order ${order.order_number}, total ${money(order.total_cents, order.currency)} ${order.currency}.`);
  const isTransfer = order.payment_provider === "etransfer";
  return <main className="checkout-page"><section className="checkout-shell"><div className="checkout-summary"><span className="checkout-brand">GOOM <small>EVENT PRODUCTION</small></span><p className="section-eyebrow"><span />{isTransfer ? "e-Transfer order" : "Secure checkout"}</p><h1>{event?.title || "Event tickets"}</h1><p><Clock3 />{isTransfer ? "Reservation held for 24 hours pending verification" : "Reservation held for 15 minutes"}</p><div className="checkout-lines">{(items || []).map((item) => <div key={item.ticket_type_id}><span>{item.quantity} × {names.get(item.ticket_type_id) || "Ticket"}</span><strong>{money(item.total_cents, order.currency)}</strong></div>)}<div><span>Subtotal</span><strong>{money(order.subtotal_cents, order.currency)}</strong></div><div><span>Service fee</span><strong>{money(order.fees_cents, order.currency)}</strong></div><div className="checkout-total"><span>Total</span><strong>{money(order.total_cents, order.currency)} {order.currency}</strong></div></div><p>Order {order.order_number}<br />Tickets for {order.customer_email}</p>{event && <Link href={`/events/${event.slug}`}>← Return to event</Link>}</div>{isTransfer ? <div className="payment-box etransfer-box">{order.status === "paid" ? <><div className="payment-title"><ShieldCheck /><div><h2>Payment approved</h2><p>Your tickets have been generated and sent to {order.customer_email}.</p></div></div><Link className="button" href={`/checkout/success?order=${token}`}>View your tickets</Link></> : <><div className="payment-title"><Landmark /><div><h2>Complete your e-Transfer</h2><p>Your order is pending. Tickets and QR codes are issued only after GOOM verifies the transfer.</p></div></div><ol className="etransfer-steps"><li><span>1</span><div>Send exactly <strong>{money(order.total_cents, order.currency)} {order.currency}</strong> by e-Transfer to <a href={`mailto:${transferEmail}`}>{transferEmail}</a>.</div></li><li><span>2</span><div>Include order <strong>{order.order_number}</strong> in the transfer message.</div></li><li><span>3</span><div>Send the payment proof to WhatsApp <strong>{transferWhatsapp}</strong>.</div></li></ol>{whatsappDigits && <a className="button" href={`https://wa.me/${whatsappDigits}?text=${whatsappMessage}`} target="_blank" rel="noreferrer"><MessageCircle />Send proof by WhatsApp</a>}<p className="secure-note"><ShieldCheck />Do not send another payment if you already completed this transfer.</p></>}</div> : <CheckoutPayment orderToken={token} amountCents={order.total_cents} currency={order.currency} customerName={order.customer_name} customerEmail={order.customer_email} customerPhone={order.customer_phone} />}</section></main>;
}
