"use client";
import { useEffect, useRef, useState } from "react";
import { CreditCard, LockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";

declare global { interface Window { Square?: { payments: (applicationId: string, locationId: string) => Promise<{ card: () => Promise<{ attach: (selector: string) => Promise<void>; tokenize: () => Promise<{ status: string; token?: string; errors?: unknown[] }>; destroy: () => Promise<void> }> }> } } }

export function CheckoutPayment({ orderToken }: { orderToken: string }) {
  const router = useRouter();
  const [provider, setProvider] = useState<"loading" | "mock" | "square" | "error">("loading"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const cardRef = useRef<{ tokenize: () => Promise<{ status: string; token?: string }>; destroy: () => Promise<void> } | null>(null);
  useEffect(() => { let cancelled = false; let script: HTMLScriptElement | null = null; (async () => { const configResponse = await fetch("/api/payments/square/config"); const config = await configResponse.json(); if (!configResponse.ok) { setProvider("error"); return; } if (config.provider === "mock") { setProvider("mock"); return; }
    script = document.createElement("script"); script.src = config.environment === "production" ? "https://web.squarecdn.com/v1/square.js" : "https://sandbox.web.squarecdn.com/v1/square.js"; script.async = true; script.onload = async () => { if (cancelled || !window.Square) return; try { const payments = await window.Square.payments(config.applicationId, config.locationId); const card = await payments.card(); await card.attach("#square-card-container"); cardRef.current = card; setProvider("square"); } catch { setProvider("error"); } }; document.head.appendChild(script);
    })(); return () => { cancelled = true; void cardRef.current?.destroy(); script?.remove(); }; }, []);
  async function pay(sourceId: string) { setBusy(true); setError(""); const response = await fetch("/api/payments/charge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderToken, sourceId }) }); const data = await response.json(); if (!response.ok || data.status === "failed") { setError(data.error || "Payment could not be completed. Try again."); setBusy(false); return; } router.push(`/checkout/success?order=${encodeURIComponent(orderToken)}`); }
  async function submitSquare() { const result = await cardRef.current?.tokenize(); if (!result?.token || result.status !== "OK") { setError("Please review your card details."); return; } await pay(result.token); }
  return <div className="payment-box"><div className="payment-title"><CreditCard /><div><h2>Secure payment</h2><p>Card details are tokenized by Square and never stored by GOOM.</p></div></div>{provider === "loading" && <p>Loading secure payment…</p>}{provider === "error" && <p className="checkout-error">Online payment is temporarily unavailable.</p>}<div id="square-card-container" className={provider === "square" ? "" : "is-hidden"} />{provider === "square" && <button className="button" disabled={busy} onClick={submitSquare}>{busy ? "Processing…" : "Pay securely"}</button>}{provider === "mock" && <div className="mock-payments"><p>Development payment simulator</p><button className="button" disabled={busy} onClick={() => pay("mock-success")}>Simulate successful payment</button><button className="outline-link" disabled={busy} onClick={() => pay("mock-failure")}>Simulate failed payment</button></div>}{error && <p className="checkout-error">{error}</p>}<p className="secure-note"><LockKeyhole />Encrypted and securely processed.</p></div>;
}
