import { notFound } from "next/navigation";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { createClient } from "@/lib/supabase/server";
import type { EventRecord, TicketTypeRecord } from "@/lib/supabase/types";
import { deleteTicketType, saveTicketType, updateEventSales } from "./actions";

const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
export default async function EventTicketsAdmin({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const { id } = await params; const query = await searchParams; const supabase = await createClient(); if (!supabase) notFound();
  const [{ data: eventData }, { data: typesData }] = await Promise.all([supabase.from("events").select("*").eq("id", id).maybeSingle(), supabase.from("ticket_types").select("*").eq("event_id", id).order("sort_order")]);
  if (!eventData) notFound(); const event = eventData as EventRecord; const types = (typesData || []) as TicketTypeRecord[];
  const { data: paidOrders } = await supabase.from("orders").select("subtotal_cents").eq("event_id", id).in("status", ["paid","partially_refunded","refunded"]);
  const { count: checkedIn } = await supabase.from("tickets").select("id", { count: "exact", head: true }).eq("event_id",id).eq("status","used");
  const sold = types.reduce((sum,type)=>sum+type.quantity_sold,0); const revenue = (paidOrders || []).reduce((sum,order)=>sum+order.subtotal_cents,0); const totalCapacity = event.capacity ?? types.reduce((sum,type)=>sum+type.quantity_total,0);
  return <><AdminPageHeader eyebrow="Ticketing" title={`${event.title} tickets`} description="Control capacity, on-sale dates, prices and availability. Inventory reservations are atomic to prevent overselling." />
    {query.saved && <p className="admin-success">Ticket settings saved.</p>}{query.error && <p className="admin-form-error">The ticket type could not be changed. Ticket types with order history cannot be deleted.</p>}
    <section className="admin-stats ticket-report-stats"><div><span>Tickets sold</span><strong>{sold}</strong></div><div><span>Checked in</span><strong>{checkedIn || 0}</strong></div><div><span>Remaining</span><strong>{Math.max(0,totalCapacity-sold)}</strong></div><div><span>Gross sales</span><strong>${(revenue/100).toLocaleString("en-CA",{minimumFractionDigits:2})}</strong></div></section><form action={updateEventSales.bind(null, id)} className="admin-editor admin-ticket-sales"><div className="admin-form-grid"><label>Event capacity<input name="capacity" type="number" min="0" defaultValue={event.capacity ?? ""} placeholder="Optional overall limit" /></label><label className="admin-check"><input name="sales_enabled" type="checkbox" defaultChecked={event.sales_enabled} /> Enable direct ticket sales</label></div><div className="admin-form-actions"><button className="admin-primary-button">Save sales settings</button></div></form>
    <section className="admin-content-stack"><form action={saveTicketType.bind(null, id, null)} className="admin-record-card"><div className="admin-record-heading"><div><span>New ticket type</span><h2>Create admission option</h2></div></div><TicketFields /><button className="admin-primary-button">Create ticket type</button></form>
      {types.map((ticket) => <form action={saveTicketType.bind(null, id, ticket.id)} className="admin-record-card" key={ticket.id}><div className="admin-record-heading"><div><span>{ticket.active ? "On sale" : "Inactive"}</span><h2>{ticket.name}</h2></div><strong>{ticket.quantity_sold} sold · {ticket.quantity_total - ticket.quantity_sold - ticket.quantity_reserved} available · {ticket.quantity_reserved} held</strong></div><TicketFields ticket={ticket} /><div className="admin-form-actions"><button className="admin-primary-button">Save</button><button formAction={deleteTicketType.bind(null, id, ticket.id)} className="admin-danger-button">Delete</button></div></form>)}
    </section></>;
}
function TicketFields({ ticket }: { ticket?: TicketTypeRecord }) { return <div className="admin-form-grid"><label>Name<input name="name" required defaultValue={ticket?.name} /></label><label>Description<input name="description" defaultValue={ticket?.description || ""} /></label><label>Price<input name="price" type="number" min="0" step="0.01" required defaultValue={ticket ? ticket.price_cents / 100 : ""} /></label><label>Currency<select name="currency" defaultValue={ticket?.currency || "CAD"}><option>CAD</option><option>USD</option></select></label><label>Quantity<input name="quantity_total" type="number" min={ticket?.quantity_sold || 0} required defaultValue={ticket?.quantity_total || ""} /></label><label>Order<input name="sort_order" type="number" defaultValue={ticket?.sort_order || 0} /></label><label>Sales start<input name="sales_start" type="datetime-local" defaultValue={localDate(ticket?.sales_start || null)} /></label><label>Sales end<input name="sales_end" type="datetime-local" defaultValue={localDate(ticket?.sales_end || null)} /></label><label>Public availability status<select name="public_availability_status" defaultValue={ticket?.public_availability_status || "automatic"}><option value="automatic">Automatic</option><option value="available">Available</option><option value="selling_fast">Selling fast</option><option value="last_tickets">Last tickets</option><option value="sold_out">Sold out</option><option value="hidden">Hidden</option></select><small>Commercial label only. Real inventory remains unchanged.</small></label><label className="admin-check"><input name="active" type="checkbox" defaultChecked={ticket?.active ?? true} /> Active</label></div>; }
