"use client";
import { useEffect, useRef, useState } from "react";
import { BrowserQRCodeReader, IScannerControls } from "@zxing/browser";
import { Camera, Keyboard, ScanLine } from "lucide-react";

type Result = { result: "valid" | "already_used" | "cancelled" | "refunded" | "invalid"; ticket_number?: string; event_name?: string; ticket_type?: string; customer?: string; checked_in_at?: string; checked_in_by?: string };
export function TicketScanner() {
  const video = useRef<HTMLVideoElement>(null); const controls = useRef<IScannerControls | null>(null); const [camera, setCamera] = useState(false); const [value, setValue] = useState(""); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => () => controls.current?.stop(), []);
  async function lookup(raw: string, checkIn = false) { if (!raw || busy) return; setBusy(true); const response = await fetch("/api/admin/scanner", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value: raw, checkIn }) }); const data = await response.json(); setResult(data); setBusy(false); controls.current?.stop(); setCamera(false); }
  async function startCamera() { setResult(null); setCamera(true); const reader = new BrowserQRCodeReader(); try { controls.current = await reader.decodeFromConstraints({ video: { facingMode: { ideal: "environment" } } }, video.current!, (scan) => { if (scan) lookup(scan.getText()); }); } catch { setCamera(false); setResult({ result: "invalid" }); } }
  const label = result?.result === "valid" ? "VALID TICKET" : result?.result === "already_used" ? "ALREADY USED" : result?.result?.toUpperCase();
  return <div className="scanner-layout"><section className="scanner-camera"><div className="scanner-viewport">{camera ? <video ref={video} muted playsInline /> : <div><ScanLine /><p>Camera preview</p></div>}<span /></div><button className="admin-primary-button" onClick={camera ? () => { controls.current?.stop(); setCamera(false); } : startCamera}><Camera />{camera ? "Stop camera" : "Scan with camera"}</button></section><section className="scanner-manual"><h2><Keyboard />Manual lookup</h2><p>Enter a ticket number, secure token, or paste the complete QR URL.</p><form onSubmit={(event) => { event.preventDefault(); lookup(value); }}><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="GOOM-MICH-000001" /><button className="admin-secondary-button" disabled={busy}>Find ticket</button></form>{result && <div className={`scan-result ${result.result}`}><span>{label}</span>{result.ticket_number && <><h3>{result.ticket_number}</h3><p><strong>{result.event_name}</strong><br />{result.ticket_type}<br />{result.customer}</p></>}{result.result === "valid" && <button className="admin-primary-button" disabled={busy} onClick={() => lookup(value || result.ticket_number || "", true)}>Check in</button>}{result.result === "already_used" && <p>Checked in {result.checked_in_at ? new Date(result.checked_in_at).toLocaleString() : "previously"}<br />{result.checked_in_by || "Administrator"}</p>}</div>}</section></div>;
}
