import Link from "next/link";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/ticketing/core";
import type { OrderStatus } from "@/lib/supabase/types";

export default async function OrdersPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { const query = await searchParams; const supabase = await createClient();
  let request = supabase?.from("orders").select("*").order("created_at", { ascending: false }).limit(200); if (query.status && request) request = request.eq("status", query.status as OrderStatus); if (query.event && request) request = request.eq("event_id", query.event); if (query.from && request) request = request.gte("created_at", `${query.from}T00:00:00`); if (query.to && request) request = request.lte("created_at", `${query.to}T23:59:59.999`); if (query.q && request) request = request.or(`order_number.ilike.%${query.q.replace(/[%(),]/g, "")}%,customer_email.ilike.%${query.q.replace(/[%(),]/g, "")}%`); const { data: orders } = request ? await request : { data: [] };
  const { data: events } = supabase ? await supabase.from("events").select("id,title").order("title") : { data: [] }; const eventNames = new Map((events || []).map((event) => [event.id,event.title]));
  const orderIds = (orders || []).map((order)=>order.id); const { data: items } = orderIds.length && supabase ? await supabase.from("order_items").select("order_id,quantity").in("order_id",orderIds) : { data: [] }; const ticketCounts = new Map<string,number>(); (items || []).forEach((item)=>ticketCounts.set(item.order_id,(ticketCounts.get(item.order_id)||0)+item.quantity));
  return <><AdminPageHeader eyebrow="Ticketing" title="Orders" description="Paid, pending, complimentary and refunded ticket orders." action={<Link href="/admin/orders/complimentary" className="admin-primary-button">Create complimentary</Link>} /><form className="admin-order-filters"><input name="q" defaultValue={query.q} placeholder="Email or order number" /><select name="event" defaultValue={query.event || ""}><option value="">All events</option>{events?.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select><select name="status" defaultValue={query.status || ""}><option value="">All statuses</option>{["pending","paid","failed","cancelled","refunded","partially_refunded"].map((status) => <option key={status}>{status}</option>)}</select><input name="from" type="date" defaultValue={query.from} aria-label="Orders from date" /><input name="to" type="date" defaultValue={query.to} aria-label="Orders to date" /><button className="admin-secondary-button">Filter</button></form><div className="admin-table admin-orders-table"><div className="admin-table-head"><span>Order</span><span>Customer</span><span>Event</span><span>Tickets</span><span>Total</span><span>Status</span><span>Date</span><span /></div>{(orders || []).map((order) => <div className="admin-table-row" key={order.id}><div><strong>{order.order_number}</strong><small>{order.payment_type}</small></div><div><strong>{order.customer_name}</strong><small>{order.customer_email}</small></div><span>{eventNames.get(order.event_id) || "Event"}</span><strong>{ticketCounts.get(order.id)||0}</strong><strong>{money(order.total_cents,order.currency)}</strong><em className={`admin-status ${order.status}`}>{order.status}</em><span>{new Date(order.created_at).toLocaleDateString()}</span><Link href={`/admin/orders/${order.id}`}>View →</Link></div>)}</div></>;
}
