import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/ticketing/core";
import { refundOrder } from "../actions";

export default async function OrderDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) { const { id } = await params; const query = await searchParams; const supabase = await createClient(); if (!supabase) notFound();
  const { data: order } = await supabase.from("orders").select("*").eq("id", id).maybeSingle(); if (!order) notFound(); const [{ data: event }, { data: tickets }, { data: items }] = await Promise.all([supabase.from("events").select("title").eq("id",order.event_id).single(),supabase.from("tickets").select("*").eq("order_id",id).order("ticket_number"),supabase.from("order_items").select("*").eq("order_id",id)]); const typeIds = [...new Set([...(tickets || []).map((ticket)=>ticket.ticket_type_id),...(items || []).map((item)=>item.ticket_type_id)])]; const { data: types } = typeIds.length ? await supabase.from("ticket_types").select("id,name").in("id",typeIds) : { data: [] }; const typeNames = new Map((types || []).map((type)=>[type.id,type.name]));
  return <><AdminPageHeader eyebrow="Order detail" title={order.order_number} description={`${event?.title || "Event"} · ${order.status}`} action={<Link href="/admin/orders" className="admin-secondary-button">Back to orders</Link>} />{query.created && <p className="admin-success">Complimentary tickets created.</p>}{query.refund && <p className="admin-success">Refund submitted. Square will confirm its final status by webhook.</p>}{query.error && <p className="admin-form-error">This refund could not be completed.</p>}
  <section className="order-detail-grid"><article className="admin-record-card"><h2>Customer</h2><dl><div><dt>Name</dt><dd>{order.customer_name}</dd></div><div><dt>Email</dt><dd>{order.customer_email}</dd></div><div><dt>Phone</dt><dd>{order.customer_phone || "—"}</dd></div></dl></article><article className="admin-record-card"><h2>Payment</h2><dl><div><dt>Total</dt><dd>{money(order.total_cents,order.currency)}</dd></div><div><dt>Provider</dt><dd>{order.payment_provider}</dd></div><div><dt>Status</dt><dd>{order.status}</dd></div><div><dt>Payment ID</dt><dd className="break-value">{order.provider_payment_id || "—"}</dd></div></dl>{order.status === "paid" && order.total_cents > 0 && <form action={refundOrder.bind(null,order.id)}><button className="admin-danger-button">Refund full order</button></form>}</article></section>
  <section className="admin-record-card order-tickets"><h2>Tickets</h2>{tickets?.length ? tickets.map((ticket)=><div key={ticket.id}><div><strong>{ticket.ticket_number}</strong><span>{typeNames.get(ticket.ticket_type_id)} · {ticket.attendee_name}</span></div><em className={`admin-status ${ticket.status}`}>{ticket.status}</em><Link href={`/tickets/${ticket.verification_token}`} target="_blank">Open ticket ↗</Link></div>) : <p>No tickets have been generated. Pending orders require provider confirmation.</p>}</section></>;
}
